export default {
  // ENTRY FILE FOR REACT APPLICATION
  APP_ENTRY_DIRECTORY: './client/app',

  // APP CONFIG FOLDER URL
  APP_CONFIG_DIRECTORY: './client/config',

  // APP COMPONENTS FOLDER URL
  APP_COMPONENTS_DIRECTORY: './client/app/components',

  // APP PAGES FOLDER URL
  APP_PAGES_DIRECTORY: './client/app/pages',

  // BUILD FOLDER URL FOR REACT APPLICATION
  BUILD_DIRECTORY: './build',

  // FONTS FOLDER URL FOR REACT APPLICATION
  FONTS_DIRECTORY: 'fonts',

  // SCRIPTS FOLDER URL FOR REACT APPLICATION
  SCRIPTS_DIRECTORY: 'js',

  // STYLES FOLDER URL FOR REACT APPLICATION
  STYLES_DIRECTORY: 'styles',

  // IMAGES FOLDER URL FOR REACT APPLICATION
  IMAGES_DIRECTORY: 'img',

  // COMMON ASSETS FOLDER URL FOR REACT APPLICATION
  ASSETS_DIRECTORY: './client/assets',

  // HTML FILE URL FOR REACT APPLICATION
  HTML_DIRECTORY: './client/public',

  // DEVELOPMENT SERVER URL FOR REACT APPLICATION
  DEV_SERVER_URL: 'http://localhost:3000',

  // PRODUCTION SERVER URL FOR REACT APPLICATION
  PRODUCTION_SERVER_URL: 'http://befront.io',

  // WEBPACK IMAGE URL FOR COMMAND LINE
  WEBPACK_NOTIFIER_IMG: './webpack-logo.png'
};