export default {
    // ENTRY FILE FOR REACT APPLICATION
    APP_ENTRY_DIRECTORY: './src',
  
    // APP CONFIG FOLDER URL
    APP_CONFIG_DIRECTORY: './src/config',

    // APP API FOLDER URL
    APP_API_DIRECTORY: './src/app/api',

    // APP UTILS FOLDER URL
    APP_UTILS_DIRECTORY: './src/app/utils',
  
    // APP COMPONENTS FOLDER URL
    APP_COMPONENTS_DIRECTORY: './src/app/components',
  
    // APP MODULES FOLDER URL
    APP_MODULES_DIRECTORY: './src/app/modules',
  
    // BUILD FOLDER URL FOR REACT APPLICATION
    BUILD_DIRECTORY: './build',
  
    // FONTS FOLDER URL FOR REACT APPLICATION
    FONTS_DIRECTORY: 'fonts',
  
    // SCRIPTS FOLDER URL FOR REACT APPLICATION
    SCRIPTS_DIRECTORY: 'js',
  
    // STYLES FOLDER URL FOR REACT APPLICATION
    STYLES_DIRECTORY: 'styles',
  
    // IMAGES FOLDER URL FOR REACT APPLICATION
    IMAGES_DIRECTORY: 'img',
  
    // COMMON ASSETS FOLDER URL FOR REACT APPLICATION
    ASSETS_DIRECTORY: './src/assets',
  
    // HTML FILE URL FOR REACT APPLICATION
    HTML_DIRECTORY: './src/public',
  
    // DEVELOPMENT SERVER URL FOR REACT APPLICATION
    DEV_SERVER_URL: 'http://localhost:3000/',
  
    // PRODUCTION SERVER URL FOR REACT APPLICATION
    PRODUCTION_SERVER_URL: 'http://befront.io/',
  
    // WEBPACK IMAGE URL FOR COMMAND LINE
    WEBPACK_NOTIFIER_IMG: './webpack-logo.png'
};