const REGISTER_BY_EMAIL = 'auth/REGISTER_BY_EMAIL';
const REGISTER_BY_EMAIL_SUCCESS = 'auth/REGISTER_BY_EMAIL_SUCCESS';
const REGISTER_BY_EMAIL_ERROR = 'auth/REGISTER_BY_EMAIL_ERROR';

export default {
    REGISTER_BY_EMAIL,
    REGISTER_BY_EMAIL_SUCCESS,
    REGISTER_BY_EMAIL_ERROR
};