export default {
    // ENTRY FILE FOR REACT APPLICATION
    APP_ENTRY_DIRECTORY: './src/admin',
  
    // APP CONFIG FOLDER URL
    APP_CONFIG_DIRECTORY: './src/admin/config',
  
    // APP SHARED COMPONENTS FOLDER URL
    APP_SHARED_COMPONENTS_DIRECTORY: './src/shared/components',
  
    // APP COMPONENTS FOLDER URL
    APP_COMPONENTS_DIRECTORY: './src/admin/app/components',
  
    // APP PAGES FOLDER URL
    APP_PAGES_DIRECTORY: './src/admin/app/pages',
  
    // BUILD FOLDER URL FOR REACT APPLICATION
    BUILD_DIRECTORY: './build/admin',
  
    // FONTS FOLDER URL FOR REACT APPLICATION
    FONTS_DIRECTORY: 'fonts',
  
    // SCRIPTS FOLDER URL FOR REACT APPLICATION
    SCRIPTS_DIRECTORY: 'js',
  
    // STYLES FOLDER URL FOR REACT APPLICATION
    STYLES_DIRECTORY: 'styles',
  
    // IMAGES FOLDER URL FOR REACT APPLICATION
    IMAGES_DIRECTORY: 'img',
  
    // COMMON ASSETS FOLDER URL FOR REACT APPLICATION
    ASSETS_DIRECTORY: './src/admin/assets',
  
    // HTML FILE URL FOR REACT APPLICATION
    HTML_DIRECTORY: './src/admin/public',
  
    // DEVELOPMENT SERVER URL FOR REACT APPLICATION
    DEV_SERVER_URL: 'http://localhost:3000',
  
    // PRODUCTION SERVER URL FOR REACT APPLICATION
    PRODUCTION_SERVER_URL: 'http://befront.io',
  
    // WEBPACK IMAGE URL FOR COMMAND LINE
    WEBPACK_NOTIFIER_IMG: './webpack-logo.png'
  };